(()=>{
 let rows=[],picked=new Set(),next=null,listingReview=null,selection=[],currency=null,walletSignature='',generation=0,loading=false;
 let editingCost=null;
 function costText(c){if(!c||c.source==='invalid')return '成本：未填写';return '单个成本：'+c.paid+' '+c.symbol+' + '+(c.gasEth===null?'当时 gas 未知':c.gasEth+' ETH gas')+(c.totalCostEth?' · 含 gas 合计 '+c.totalCostEth+' ETH':'')+' · '+(c.source==='manual'?'手动填写':c.source==='chain-mint'?'链上 mint 回执均摊 · '+c.historyNote:'本机历史 mint 记录（均摊；未追踪后续转手）');}
 function showCosts(){const root=$('listing-costs');root.replaceChildren();for(const id of selection){const n=rows.find(x=>x.id===id);if(!n)continue;const box=el('div',undefined,'review-row');box.append(el('strong',n.name+' #'+n.tokenId),el('p',costText(n.cost)),button('填写 / 修改成本','quiet',()=>editCost(n)));root.append(box);}}
 function editCost(n){editingCost=n;$('cost-title').textContent=n.name+' #'+n.tokenId;$('cost-symbol').value=n.cost?.symbol||'ETH';$('cost-paid').value=n.cost?.paid??'';$('cost-gas').value=n.cost?.gasEth??'';$('cost-hash').value='';$('cost-message').textContent='可自动查询过去的链上 mint；不需要重新导入私钥。手填成本优先保留。';$('cost-dialog').showModal();}
 async function saveCost(clear=false){if(!editingCost)throw Error('请重新选择 NFT。');const item=editingCost;const result=await api('/api/nfts/cost',{itemId:item.id,clear,symbol:$('cost-symbol').value,paid:$('cost-paid').value.trim(),gasEth:$('cost-gas').value.trim()});item.cost=result.cost;invalidate();draw();if($('listing-dialog').open)showCosts();$('cost-dialog').close();}
 $('cost-form').onsubmit=e=>{e.preventDefault();busy($('cost-save'),()=>saveCost().catch(e=>{$('cost-message').textContent=e.message;}));};
 $('cost-clear').onclick=()=>busy($('cost-clear'),()=>saveCost(true).catch(e=>{$('cost-message').textContent=e.message;}));
 async function readChainCost(n,hash=''){const version=generation;const result=await api('/api/nfts/cost-chain',{itemId:n.id,rpcUrl:rpc.value,transactionHash:hash});if(version!==generation)return;n.cost=result.cost;n.costError=null;invalidate();draw();if($('listing-dialog').open)showCosts();if(editingCost===n){$('cost-symbol').value=n.cost?.symbol||'ETH';$('cost-paid').value=n.cost?.paid??'';$('cost-gas').value=n.cost?.gasEth??'';$('cost-message').textContent=n.cost?.source==='manual'?'链上记录已核验，保留你手填的成本。清除手填后可恢复链上记录。':costText(n.cost);}return result;}
 $('cost-chain').onclick=()=>busy($('cost-chain'),async()=>{if(!editingCost)return;const n=editingCost;$('cost-message').textContent='正在读取 mint 历史并核验链上回执…';try{await readChainCost(n,$('cost-hash').value.trim());}catch(e){if(editingCost===n)$('cost-message').textContent=e.message;}});
 $('cost-dialog').onclose=()=>{editingCost=null;};
 const wallet=$('nft-wallet'),chain=$('nft-chain'),rpc=$('nft-rpc');
 function invalidate(){listingReview=null;$('listing-review').replaceChildren();$('listing-authorization').hidden=true;$('listing-consent').checked=false;$('listing-start').disabled=true;}
 function reset(){generation++;rows=[];picked.clear();next=null;invalidate();if($('cost-dialog').open)$('cost-dialog').close();if($('listing-dialog').open)$('listing-dialog').close();draw();$('nft-message').textContent='点击“刷新持仓与上架状态”读取当前钱包。';}
 function sync(){const sig=JSON.stringify(state.wallets.map(w=>[w.id,w.address]));if(sig===walletSignature)return;walletSignature=sig;const old=wallet.value;wallet.replaceChildren();for(const w of state.wallets){const opt=el('option',`${w.label} · ${w.address.slice(0,8)}…${w.address.slice(-6)}`);opt.value=w.id;wallet.append(opt);}if(state.wallets.some(w=>w.id===old))wallet.value=old;reset();}
 window.mintHoldings={sync,activate:sync};
 wallet.onchange=reset;chain.onchange=()=>{rpc.value='';reset();};rpc.oninput=reset;
 $('nft-minted').onchange=()=>{picked.clear();draw();};
 const canPick=n=>n.owned!==false&&n.listingChecked&&!n.listing&&(!n.local||n.local.end*1000<Date.now())&&['erc721','erc1155'].includes(n.standard);
 function draw(){const root=$('nft-list');root.replaceChildren();const shown=rows.filter(n=>!$('nft-minted').checked||n.minted);
  if(!shown.length)root.append(el('p',rows.length?'当前筛选没有 NFT。':'暂无持仓结果，请先导入钱包并刷新。','empty'));
  for(const n of shown){const card=el('article',undefined,'project-card'),choose=el('label',undefined,'check'),checkbox=el('input');checkbox.type='checkbox';checkbox.checked=picked.has(n.id);checkbox.disabled=!canPick(n);checkbox.onchange=()=>{if(checkbox.checked)picked.add(n.id);else picked.delete(n.id);$('nft-list-selected').textContent=`批量上架（${picked.size}）`;};choose.append(checkbox,el('span',n.minted?'本软件 mint':'钱包持仓'));card.append(choose);
   const h=el('h3');h.append(externalLink(n.name,n.url));card.append(h,el('p',`#${n.tokenId} · ${n.standard.toUpperCase()}`),el('div',n.contract,'address'));
   card.append(el('p',n.owned===false?'当前未确认持有，不能上架':n.owned===true?'链上已核验持有':'OpenSea 持仓索引；上架前核验'));
   card.append(el('strong',n.listing?`已上架 · ${n.listing.price}`:!n.listingChecked?'上架状态查询失败':n.local&&n.local.end*1000>Date.now()?`${n.local.status} · ${n.local.price??n.local.priceEth} ${n.local.currency?.symbol??'ETH'}`:'未查到有效上架'));
   if(n.local?.hash)card.append(el('small',`本机订单 ${n.local.hash}`,'address'));
   const quote=el('div',undefined,'project-market'),b=button('查询地板 / 成交价','quiet',()=>busy(b,async()=>{const q=await api('/api/nfts/market',{itemId:n.id});quote.replaceChildren(el('div',`地板挂单：${priceText(q.floor)}`),el('div',`最近单件成交：${q.sales?.length?priceText(q.sales[0].price):'未取得样本'}`),el('small',`查询时间：${new Date(q.checkedUtc).toLocaleString()}`));for(const warning of q.warnings??[])quote.append(el('small',warning));}));
   card.append(el('p',costText(n.cost)));if(n.costError)card.append(el('small',n.costError));if(n.cost?.source==='chain-mint')card.append(txLink(n.cost.hash,n.chainId));const actions=el('div',undefined,'card-actions');const lookup=button('链上查 mint 成本','quiet',()=>busy(lookup,async()=>{try{await readChainCost(n);}catch(e){n.costError=e.message;draw();}}));actions.append(lookup,button('填写 / 修改成本','quiet',()=>editCost(n)),b,externalLink('OpenSea ↗',n.url));card.append(quote,actions);root.append(card);
  }$('nft-more').hidden=!next;$('nft-list-selected').textContent=`批量上架（${picked.size}）`;
 }
 async function load(more=false){if(loading)return;sync();if(!wallet.value)throw Error('请先在钱包管理中导入钱包。');loading=true;const version=++generation;try{const result=await api('/api/nfts/refresh',{walletId:wallet.value,chainId:Number(chain.value),rpcUrl:rpc.value,next:more?next:''});if(version!==generation)return;
   const map=new Map((more?rows:[]).map(n=>[n.id,n]));for(const n of result.items)map.set(n.id,n);rows=[...map.values()];picked.clear();next=result.next;draw();$('nft-message').textContent=`已读取 ${rows.length} 项${next?'，还有更多':''} · ${new Date(result.checkedAt).toLocaleString()}。${result.warnings.join(' ')}`;
   const missing=rows.filter(n=>!n.cost&&n.standard==='erc721').slice(0,10);for(const n of missing){if(version!==generation)break;$('nft-message').textContent=`已读取 ${rows.length} 项，正在核验 ${n.name} #${n.tokenId} 的历史 mint 成本…`;try{await readChainCost(n);}catch(e){if(version===generation){n.costError=e.message;draw();}}}if(version===generation)$('nft-message').textContent=`已读取 ${rows.length} 项；已尝试查询 ${missing.length} 项缺失的 mint 成本。${result.warnings.join(' ')} 未查到的可点击“链上查 mint 成本”重试或提供交易哈希。`;
  }finally{loading=false;}}
 $('nft-refresh').onclick=()=>busy($('nft-refresh'),()=>load());$('nft-more').onclick=()=>busy($('nft-more'),()=>load(true));
 $('nft-list-selected').onclick=()=>busy($('nft-list-selected'),async()=>{if(!picked.size||picked.size>20){note('请选择 1–20 项 NFT，每项出售 1 个。',true);return;}selection=[...picked];currency=null;invalidate();showCosts();$('listing-eth-rate').value='';$('listing-rate-label').hidden=true;const version=generation;$('listing-selection').textContent=`已选择 ${selection.length} 项，统一售价，每项出售 1 个。可取消后分批设置不同价格。`;$('listing-price').value='';$('listing-price').disabled=true;$('listing-preview').disabled=true;$('listing-price-label').textContent='每项售价 · 正在识别币种';$('listing-currency').textContent='正在核对 OpenSea 报价币种与链上精度…';$('listing-dialog').showModal();try{const result=await api('/api/listings/currency',{itemIds:selection,rpcUrl:rpc.value});if(version!==generation||!$('listing-dialog').open)return;currency=result.currency;$('listing-rate-label').hidden=currency.native;$('listing-rate-note').textContent=`填入 1 ETH ≈ 多少 ${currency.symbol}。仅用于盈亏估算，不改变挂单币种和售价。`;$('listing-price-label').textContent=`每项售价 · ${currency.symbol}`;$('listing-currency').textContent=`售价与到账币种：${currency.symbol} · 最多 ${currency.decimals} 位小数。${currency.native?'原生 ETH':`代币合约：${currency.address}`}。gas 单独使用 ETH；不自动换算旧售价。`;$('listing-price').disabled=false;$('listing-preview').disabled=false;}catch(e){if(version===generation&&$('listing-dialog').open)$('listing-currency').textContent=e.message;}});
 for(const id of ['listing-price','listing-hours','listing-gas','listing-eth-rate'])$(id).oninput=invalidate;
 $('listing-dialog').onclose=()=>{currency=null;invalidate();};
 $('listing-preview').onclick=()=>busy($('listing-preview'),async()=>{if(!currency)throw Error('请先识别并核对上架币种。');invalidate();const inputs=JSON.stringify([selection,$('listing-price').value,$('listing-hours').value,$('listing-gas').value,rpc.value,$('listing-eth-rate').value]);const result=await api('/api/listings/preview',{itemIds:selection,currency,price:$('listing-price').value.trim(),hours:Number($('listing-hours').value),maxGasEth:$('listing-gas').value.trim(),ethRate:$('listing-eth-rate').value.trim(),rpcUrl:rpc.value});
  if(!$('listing-dialog').open||inputs!==JSON.stringify([selection,$('listing-price').value,$('listing-hours').value,$('listing-gas').value,rpc.value,$('listing-eth-rate').value]))throw Error('设置已更改，请重新预览。');listingReview=result.reviewId;const box=$('listing-review');box.append(el('p',`上架币种：${result.currency.symbol}。本批授权 gas 总预算：${result.maxBudget} ETH；其他任务预留：${result.reservedEth} ETH。有效期 ${result.hours} 小时。`));
  for(const r of result.rows){const item=el('div',undefined,'review-row');item.append(el('strong',`${r.name} #${r.tokenId}`),el('p',`售价 ${r.price} ${result.currency.symbol} → 扣订单费用后预计到账 ${r.net} ${result.currency.symbol}（授权 gas 另付 ETH，不从此数额换算扣除）`),el('p',r.approvalNeeded?`需要${r.standard==='erc721'?'单个 NFT 授权':'整个系列授权'}，预估 gas 上限 ${r.estimatedGas} ETH`:'已有授权，无需新增授权交易'));item.append(el('p',costText(r.cost)));if(r.outcome?.status==='ok'){item.append(el('p',`保本参考售价：${r.outcome.breakEven} ${r.outcome.symbol}（按当前费用估算）`),el('strong',`按挂单价成交后预计${r.outcome.profit.startsWith('-')?'亏损':'盈利'}：${r.outcome.profit} ${r.outcome.symbol}`),el('p',`计入成本及本次授权 gas 估算上限：${r.outcome.total} ${r.outcome.symbol}。${r.outcome.rate?'按手填换算价 1 ETH = '+r.outcome.rate+' '+r.outcome.symbol+'。':''}实际成交和费用可能不同。`));}else item.append(el('p',r.outcome?.note||'成本未知，暂不计算盈亏。'));for(const f of r.fees)item.append(el('small',`费用 ${f.bps/100}% · ${f.amountText} ${result.currency.symbol} → ${f.recipient}`,'address'));box.append(item);}$('listing-authorization').hidden=false;
 });
 $('listing-consent').onchange=()=>{$('listing-start').disabled=!listingReview||!$('listing-consent').checked;};
 $('listing-start').onclick=()=>busy($('listing-start'),async()=>{await api('/api/listings/start',{reviewId:listingReview,confirm:$('listing-consent').checked});$('listing-dialog').close();picked.clear();show('tasks');await refresh();note('上架任务已启动，查看运行任务中的逐项进度。完成后返回“我的 NFT”刷新。');});
})();
